In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #return a new array of given shape and type, filled with zeros.

In [3]:
a.ndim

1

In [4]:
a

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
b = np.zeros((3,4))

In [7]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b.ndim

2

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5, dtype=int) #return a new array of given shape and type, filled with ones

array([1, 1, 1, 1, 1])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.twos(5) #does not exist in numpy


AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
arr = np.zeros((3,4))
         

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
#three dimensional array
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr=np.zeros((1,3,4))

In [ ]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
b=np.zeros((1,3,3))

In [ ]:
b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
b.ndim

3

In [ ]:
c = np.zeros((1,1,1,3,3))

In [ ]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [ ]:
c.ndim

5

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = arr+5

In [ ]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a + 2

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [ ]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(3) #Return a 2-0 array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.empty((3, 4)) #Return a new array of given shape and type,without initializing entries. it means entries in the array can be anything random

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
#optional >> random module
import random
random.choice((1, 2, 3, 4, 5))

2

In [ ]:
random.choice("komal")

'a'

In [ ]:
random.randrange(1, 10)

5

In [ ]:
random.random() #a random no generated between 0 (included) and 1 (excluded)

0.018237457867173124

In [ ]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [ ]:
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[5, 4, 3, 2, 1]

In [ ]:
random.uniform(7,14)

13.83736078168228

In [ ]:
#random numbers related concept in numpy
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.29877950328987435

In [ ]:
np.random.random_sample((5, ))#1 dim array of 5 random nos

array([0.13180016, 0.26926599, 0.11251365, 0.72933121, 0.03988419])

In [ ]:
np.random.rand(1)

array([0.83044728])

In [ ]:
np.random.rand(2, 3)

array([[0.42583284, 0.58803325, 0.85909574],
       [0.11427998, 0.20692236, 0.3793909 ]])

In [ ]:
np.random.randn(2,3) #return a sample (or samples ) from the "standard normal" distribution

array([[-0.22052631, -0.98255378,  0.13156537],
       [-0.8614893 ,  0.44389832, -0.80153228]])

In [ ]:
np.random.randint(1,4)

2

In [ ]:
np.random.randint(1, 5, size = (3,4)) #start from 1 and end at 5-1 and give array of shape 3,4

array([[3, 2, 1, 3],
       [1, 1, 3, 2],
       [4, 1, 2, 1]], dtype=int32)

In [ ]:
arr = np.random.randint(1,5, size = (3,4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr

array([[3, 3, 2, 1],
       [3, 4, 1, 4],
       [1, 3, 4, 3]], dtype=int32)

In [ ]:
#reshaping of array
arr1 = arr.reshape(2,6) #returns an array containing the same data with a new shape

In [ ]:
arr1

array([[3, 3, 2, 1, 3, 4],
       [1, 4, 1, 3, 4, 3]], dtype=int32)

In [ ]:
arr1.size

12

In [ ]:
arr1.shape

(2, 6)

In [ ]:
arr1.ndim

2

In [ ]:
#array size will never change, always reshape parameter should be multiplication of original array size
arr

array([[3, 3, 2, 1],
       [3, 4, 1, 4],
       [1, 3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [ ]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [ ]:
arr.reshape(3,4)

array([[3, 3, 2, 1],
       [3, 4, 1, 4],
       [1, 3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(4,3)

array([[3, 3, 2],
       [1, 3, 4],
       [1, 4, 1],
       [3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(1,12)

array([[3, 3, 2, 1, 3, 4, 1, 4, 1, 3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(12,1)

array([[3],
       [3],
       [2],
       [1],
       [3],
       [4],
       [1],
       [4],
       [1],
       [3],
       [4],
       [3]], dtype=int32)

In [ ]:
arr.reshape(4,2)

ValueError: cannot reshape array of size 12 into shape (4,2)

In [ ]:
arr.reshape(4, -1) #case when you don,t know what should be the row or column count ,#use any negative value for rows or columns

array([[3, 3, 2],
       [1, 3, 4],
       [1, 4, 1],
       [3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(4,-100)

array([[3, 3, 2],
       [1, 3, 4],
       [1, 4, 1],
       [3, 4, 3]], dtype=int32)

In [ ]:
arr

array([[3, 3, 2, 1],
       [3, 4, 1, 4],
       [1, 3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(12,1)

array([[3],
       [3],
       [2],
       [1],
       [3],
       [4],
       [1],
       [4],
       [1],
       [3],
       [4],
       [3]], dtype=int32)

In [ ]:
arr.reshape(12,1).base #to see the original array

array([[3, 3, 2, 1],
       [3, 4, 1, 4],
       [1, 3, 4, 3]], dtype=int32)

In [ ]:
arr.reshape(2,2,3) #multiplication should be equals to arr size

array([[[3, 3, 2],
        [1, 3, 4]],

       [[1, 4, 1],
        [3, 4, 3]]], dtype=int32)

In [ ]:
arr.reshape(1,2,2,3)

array([[[[3, 3, 2],
         [1, 3, 4]],

        [[1, 4, 1],
         [3, 4, 3]]]], dtype=int32)

In [ ]:
arr.reshape(1,2,2,3).ndim

4

In [ ]:
arr.reshape(4,3,1) #3 rows 1 column repeated 4 times in the third dimension

array([[[3],
        [3],
        [2]],

       [[1],
        [3],
        [4]],

       [[1],
        [4],
        [1]],

       [[3],
        [4],
        [3]]], dtype=int32)

In [ ]:
#conditions on array
arr1 = np.random.randint(1,10, (5,6))

In [ ]:
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr1.size

30

In [ ]:
arr1.ndim

2

In [ ]:
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
arr1 > 3

array([[ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False, False,  True],
       [False,  True,  True,  True, False,  True],
       [False, False,  True, False,  True,  True],
       [False,  True, False, False,  True,  True]])

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr.size

12

In [ ]:
arr1[arr1 > 3] #select all the elements of arr1 where the condition is true

array([7, 9, 5, 7, 5, 9, 6, 9, 7, 9, 9, 5, 9, 6, 4, 7, 6, 6, 9],
      dtype=int32)

In [ ]:
arr1[arr1 < 3]

array([2, 2, 1, 2, 2, 1, 2, 1, 2], dtype=int32)

In [ ]:
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
#to access elements in an array

In [ ]:
arr1[0]

array([7, 9, 5, 7, 5, 9], dtype=int32)

In [ ]:
arr1[1]

array([2, 6, 9, 2, 1, 7], dtype=int32)

In [ ]:
arr[1][2]

np.int32(1)

In [ ]:
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
arr1[3][1]

np.int32(1)

In [ ]:
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
#from 0th row to 2nd row
arr1[0:3]

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9]], dtype=int32)

In [ ]:
#0 to 2nd row and 0th and 2nd column
arr1[0:3,[0,2]]

array([[7, 5],
       [2, 9],
       [2, 9]], dtype=int32)

In [ ]:
#slicing on both rows and column togehter
arr1

array([[7, 9, 5, 7, 5, 9],
       [2, 6, 9, 2, 1, 7],
       [2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
arr1[0:3, 1:3]

array([[9, 5],
       [6, 9],
       [9, 9]], dtype=int32)

In [ ]:
arr1[0:3, [0,1]]

array([[7, 9],
       [2, 6],
       [2, 9]], dtype=int32)

In [ ]:
arr1[0]

array([7, 9, 5, 7, 5, 9], dtype=int32)

In [ ]:
arr1[0:3,[0, 1]]

array([[7, 9],
       [2, 6],
       [2, 9]], dtype=int32)

In [ ]:
arr1[0,[1,3]]

array([9, 7], dtype=int32)

In [ ]:
arr1[2:4, [0,3]]

array([[2, 5],
       [3, 2]], dtype=int32)

In [ ]:
arr1[2:5]

array([[2, 9, 9, 5, 2, 9],
       [3, 1, 6, 2, 4, 7],
       [1, 6, 3, 2, 6, 9]], dtype=int32)

In [ ]:
arr1[2:5, 0:2]

array([[2, 9],
       [3, 1],
       [1, 6]], dtype=int32)

In [ ]:
#mathematical operations on two arrays
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,2,(3,3))

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [ ]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
arr1+arr2 #indexwise addition element

array([[2, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [ ]:
arr1-arr2

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
arr1*arr2

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [ ]:
arr1,arr2

(array([[1, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=int32),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int32))

In [ ]:
arr1/arr2

array([[1., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1/0

C:\Users\komal\AppData\Local\Temp\ipykernel_8092\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#matrix multiplication >> matrix is a specialised 2-d array
#matrix multiplication is different from index wise multiplication

In [ ]:
arr1 @ arr2

array([[5, 5, 5],
       [6, 6, 6],
       [6, 6, 6]], dtype=int32)

In [ ]:
np.dot(arr1, arr2) #another way of matrix multiplication

array([[5, 5, 5],
       [6, 6, 6],
       [6, 6, 6]], dtype=int32)

In [ ]:
arr1 * arr2

NameError: name 'arr1' is not defined

In [ ]:
#broadcasting
arr = np.zeros((3,4))

NameError: name 'np' is not defined

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr-5

NameError: name 'arr' is not defined

In [ ]:
a = np.array([1,2,3,4])

NameError: name 'np' is not defined

In [ ]:
#transpose >> converting rows to column and column to rows

In [ ]:
a = np.array([[1,2,3,4]])

NameError: name 'np' is not defined

In [ ]:
a

NameError: name 'a' is not defined

In [ ]:
a.T

NameError: name 'a' is not defined

In [ ]:
arr1

NameError: name 'arr1' is not defined

In [ ]:
arr1.T

NameError: name 'arr1' is not defined