In [6]:
import numpy as np

In [7]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [8]:
import numpy as np


In [9]:
import numpy as np

arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))


In [10]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [11]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [12]:
arr1.flatten() #return a copy of the array collapsed into one dimension.

array([1, 2, 1, 1, 2, 1, 1, 1, 1], dtype=int32)

In [13]:
#expand dimension
arr = np.array([1,2,3,4])

In [14]:
arr

array([1, 2, 3, 4])

In [15]:
arr.ndim

1

In [17]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis, 0 means rows(x-axix), 1 means column wise

array([[1, 2, 3, 4]])

In [18]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [19]:
np.expand_dims(arr, axis=1).ndim

2

In [20]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
np.expand_dims(arr, axis=0).ndim

3

In [24]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [25]:
np.expand_dims(arr,axis=0).ndim

3

In [26]:
a = np.array([[1],[2],[3]])

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
a.ndim

2

In [29]:
#squeezing the dimension by 1 dimension
np.squeeze(a) #remove exes of length one from 'a'

array([1, 2, 3])

In [30]:
a

array([[1],
       [2],
       [3]])

In [31]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [32]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [33]:
np.repeat(arr1, 2)

array([1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [34]:
np.repeat(arr1, 2, axis=0)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [35]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [36]:
np.repeat(arr2,3,axis=0)

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [37]:
np.repeat(arr2,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [38]:
a

array([[1],
       [2],
       [3]])

In [39]:
np.roll(a,-1) #shift place

array([[2],
       [3],
       [1]])

In [40]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [41]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [42]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [44]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [45]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [46]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [47]:
arr1+arr2

array([[2, 4, 2],
       [2, 3, 2],
       [2, 2, 2]], dtype=int32)

In [48]:
arr1-arr2

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [49]:
arr1*arr2

array([[1, 4, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [50]:
arr1>arr2

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [51]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [52]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [53]:
~arr1

array([[-2, -3, -2],
       [-2, -3, -2],
       [-2, -2, -2]], dtype=int32)

In [55]:
#operations on numpy string array

d = np.array(["pw", "skills"])

In [56]:
d

array(['pw', 'skills'], dtype='<U6')

In [57]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [58]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#mathematical function

In [59]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [60]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.84147098],
       [0.84147098, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [61]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684,  0.54030231],
       [ 0.54030231, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [62]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986,  1.55740772],
       [ 1.55740772, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772,  1.55740772]])

In [63]:
np.log10(arr1)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [64]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [65]:
np.power(arr1, 3)

array([[1, 8, 1],
       [1, 8, 1],
       [1, 1, 1]], dtype=int32)

In [66]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [67]:
np.max(arr1)

np.int32(2)

In [68]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [69]:
np.mean(arr1)

np.float64(1.2222222222222223)

In [70]:
np.min(arr1)

np.int32(1)

In [71]:
np.std(arr1)

np.float64(0.41573970964154905)

In [72]:
np.var(arr1)

np.float64(0.1728395061728395)

In [73]:
arr1-arr2

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [74]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [75]:
np.multiply(arr1,arr2)

array([[1, 4, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [76]:
np.mod(arr1,arr2) #return element wise remainder

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [77]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [78]:
#sorting and searching in numpy array
e = np.array([5,6,1,2])


In [79]:
e

array([5, 6, 1, 2])

In [ ]:
np.sort(e) #return a sorted copy of an array

array([1, 2, 5, 6])

In [81]:
f = np.array([5,199,200,6,7,8])

In [82]:
f

array([  5, 199, 200,   6,   7,   8])

In [83]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [84]:
np.searchsorted(f, 170)

np.int64(6)

In [85]:
#find indices ehere elements should be inseted to maintain order
f = np.array([5,199,200,0,0,0,6,7,8])

In [86]:
f

array([  5, 199, 200,   0,   0,   0,   6,   7,   8])

In [88]:
np.count_nonzero(f)

6

In [89]:
f>0

array([ True,  True,  True, False, False, False,  True,  True,  True])

In [90]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [91]:
np.where(f>0)

(array([0, 1, 2, 6, 7, 8]),)

In [92]:
np.extract(f>0,f)

array([  5, 199, 200,   6,   7,   8])

In [93]:
f

array([  5, 199, 200,   0,   0,   0,   6,   7,   8])

In [95]:
f.byteswap() #swap the byte of the array elements

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
         432345564227567616,   504403158265495552,   576460752303423488])

In [96]:
import numpy.matlib as nm

In [97]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [98]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
#numpy as linear algebra
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [100]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [101]:
arr1 @arr2

array([[4, 5, 4],
       [4, 5, 4],
       [3, 4, 3]], dtype=int32)

In [102]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 1]], dtype=int32)

In [103]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [104]:
np.linalg.det(arr1)

np.float64(0.0)

In [109]:
np.linalg.det(arr2)

np.float64(0.0)

In [111]:
#in matrxi you can not divide another matrix,you have inverse
np.linalg.inv(arr2)

LinAlgError: Singular matrix

In [113]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [114]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [115]:
b = np.array([16,8,0])

In [116]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])

In [108]:
det = np.linalg.det(arr2)
if det == 0:
    print("Matrix is singular and cannot be inverted.")
else:
    inverse = np.linalg.inv(arr2)
    print("Inverse of the matrix:\n", inverse)


Matrix is singular and cannot be inverted.
