CRISP-DM framework -- cross - industry process for data mining
data mining means getting insighs from the data

business understanding
Problem statement:
* To predict price of House
1. area of house
2. no of rooms
* Data understanding
1. How area of house decides the price of house
Area of House increase ,price of houses increase, no of rooms increase,price increase,no of rooms increase, Area increase
explorating data analysis(EDA)
* Data preparation
* modelling
* evaluation
* Deployment
* library - A library is a collection of pre=work code, that is used to perform common task
addition, subtraction,multiplication(module,LA(module)), calculation (module)
all of these modules kept toghether ia called as package
multiple package toghether is called as library
library contains python modules and packages


In [4]:
#numpy>> stands for numerical python
#2005 by trais o.iphant
#before 2005 there were special mathematical tools(similar to Tora, Linga)

In [5]:
import numpy  as np  #as is alias


In [6]:
np.__version__

'2.1.3'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
lis = [1,2,3,"komal",3+5j] #list stoores heterogenous data

In [9]:
type(lis)

list

In [10]:
#numpy stores the data in a nmpy array
#an array is a container/data structure used to store data os same data type>>homogenous

In [11]:
#why numpy? already we have list, c is one of the fastest programming language after c++ 
#numpy is built using C >> Numpy Computation is fast
#due to array >>  since it stores only homogenous data, numpy array is faster
#since it stores homogenous data>>contiguous/ continous memory location
#mathematical computation is fast

In [12]:
l = [1,2,3,4] #numpy array is homogenous>> all elements can be integer,float,string

In [13]:
np.array(l)

array([1, 2, 3, 4])

In [14]:
arr = np.array(l) #numpy.ndarray>>n dimensional array

In [15]:
type(arr)

numpy.ndarray

In [16]:
l = [1,2.2, "komal"]

In [17]:
np.array(l)

array(['1', '2.2', 'komal'], dtype='<U32')

In [18]:
#array stores homogenous data
arr

array([1, 2, 3, 4])

In [19]:
l = [1,2,4, 3+5j]
np.array(l)

array([1.+0.j, 2.+0.j, 4.+0.j, 3.+5.j])

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr

array([1, 2, 3, 4])

In [22]:
arr.ndim #arr has only rows

1

In [23]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [24]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr1.ndim

2

In [26]:
mat = np.matrix([1,2,3,4]) #matrix is a specialised array of 2 dimension

In [27]:
type(mat)

numpy.matrix

In [28]:
mat.ndim

2

In [29]:
mat

matrix([[1, 2, 3, 4]])

In [30]:
#to undestand the dimension,see the no of opening/closing square bracket

In [31]:
np.matrix([[[1,2],[1,5],[3,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
arr3 = np.array([[[1,2],[1,5],[3,6]]])

In [ ]:
arr3

array([[[1, 2],
        [1, 5],
        [3, 6]]])

In [ ]:
arr3.ndim

3

In [ ]:
#more ways to convert array
l = [1,2,3]
np.asarray(l) #initial function asarray to convert to an array,np.array came after this

array([1, 2, 3])

In [ ]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [ ]:
#asanyarray will convert the input to an ndarray,but pass ndarray subclass throws
#if something is already an array or part of array,it will simply allows to pass through it

In [ ]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(mat)


matrix([[1, 2, 3, 4]])

In [ ]:
t = ([1,2,3],[4,5,6])

In [ ]:
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
#accessing elements of the array
arr[0]

np.int64(1)

In [ ]:
#array is mutable
arr[0] = 1000

In [ ]:
arr

array([1000,    2,    3,    4])

In [ ]:
a = arr #a and arr will point to same memory location.so if there is change is a or arr
#it will reflect to both

In [ ]:
a

array([1000,    2,    3,    4])

In [ ]:
#shallow copy>. change in one array will lead to change in another

In [ ]:
a[0] = 5000

In [ ]:
a

array([5000,    2,    3,    4])

In [ ]:
arr

array([5000,    2,    3,    4])

In [ ]:
b = arr.copy() #deep copy>> change on one array will not reflect in another

In [ ]:
b

array([5000,    2,    3,    4])

In [ ]:
#to create an array>> np.array,np.asarray,np.asany array
#multiple approaches to generate any array

In [32]:
np.fromfunction(lambda i,j:i==j,(3,3)) #construct an array by executing a function over each coordinate

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
l==2

False

In [34]:
arr1 = np.fromfunction(lambda i,j:i==j,(3,3))

In [35]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
arr1.ndim

2

In [37]:
arr1.shape #shape of array

(3, 3)

In [38]:
arr1.size #no of elements in array

9

In [40]:
#True is stored as1 and Flse 0 in python
True - False

1

In [44]:
arr2 = np.fromfunction(lambda i, j:i*j,(3,3))

In [45]:
arr2.ndim

2

In [46]:
arr2.shape

(3, 3)

In [47]:
arr2.size

9

In [48]:
for i in range(5):
    print(i)

0
1
2
3
4


In [49]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [50]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [51]:
(i for i in range(5))

<generator object <genexpr> at 0x0000021DC5A15240>

In [53]:
iterator = (i for i in range(5))

In [54]:
iterator

<generator object <genexpr> at 0x0000021DC5A14E80>

In [55]:
np.fromiter(iterator, int) #create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [56]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [ ]:
np.fromstring('22 23 24', sep = " ", dtype = int) #by default is float, values inside string should be numerical

array([22, 23, 24])

In [58]:
#for string character you have to use split
string = "Ajay, Bijay, Sanjay"
string.split(",")

['Ajay', ' Bijay', ' Sanjay']

In [59]:
np.array(string.split(","))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

In [60]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
range(10)

range(0, 10)

In [63]:
#other method of numpy >> to generate a sequence of number
np.arange(1, 10) #arrange returns evenly specified values within a given interval, by default step is 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [66]:
np.linspace(1, 5, 10) #give me 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])